import type { Metadata } from "next";

import Header from "@/components/Header";

import Favicon from "/public/favicon.ico";
import "@/styles/global.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    as="style"
                    href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css"
                />
            </head>
            <body className="overflow-y-scroll">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
